vendor = 'Islandora Foundation'
homepage = 'http://islandora.ca'
inceptionYear = '2015'
docURL = 'https://islandora.github.io/documentation/'
license = 'MIT'
projectHomepage = 'https://github.com/Islandora/Alpaca'
version = 3.0.0-SNAPSHOT

# The following properties are used by the Gradle build system
org.gradle.jvmargs = -Xmx2g
